[package]
name = "atom_str"
description = "A string interning library."
edition = "2024"
version = "0.1.0"
repository = "https://github.com/ErisianArchitect/atom_str"
readme = "README.md"
license-file = "LICENSE"
keywords = ["string", "intern", "atom"]

[dependencies]
twox-hash = "2.1.1"
